#!/usr/bin/env bash

cd `dirname $0`
LIBS_DIR=`pwd`

# eigen3
wget -O eigen-3.2.2.tar.bz2 http://bitbucket.org/eigen/eigen/get/3.2.2.tar.bz2
tar xf eigen-3.2.2.tar.bz2
rm eigen-3.2.2.tar.bz2
cd eigen*

mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=$LIBS_DIR/eigen ..
make -j8 && make install

# pcl
PCL_SOURCE_DIR=$LIBS_DIR/pcl_src
PCL_INSTALL_DIR=$LIBS_DIR/pcl

rm -rf $PCL_SOURCE_DIR $PCL_INSTALL_DIR

git clone https://github.com/PointCloudLibrary/pcl.git $PCL_SOURCE_DIR
cd $PCL_SOURCE_DIR
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=$PCL_INSTALL_DIR -DCMAKE_BUILD_TYPE=Release ..
make -j8 && make install
