#!/usr/bin/env bash

cd `dirname $0`
LIBS_DIR=`pwd`

# pcl
PCL_SOURCE_DIR=$LIBS_DIR/pcl_src
PCL_INSTALL_DIR=$LIBS_DIR/pcl

rm -rf $PCL_SOURCE_DIR $PCL_INSTALL_DIR

git clone https://github.com/PointCloudLibrary/pcl.git $PCL_SOURCE_DIR
cd $PCL_SOURCE_DIR
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=$PCL_INSTALL_DIR -DCMAKE_BUILD_TYPE=Release ..
make -j8 && make install
